### ISSUE TITLE
Theft OCR

### ISSUE THREAD

**Issue by dmadisetti** [USCSoftwareEngineeringClub/pyceratOpsRecs#3]
YES! I'm really excited about this one. It took me an ge to refind the paper, but here it is:
- https://arxiv.org/abs/1602.02697
- There's a wired article here: https://www.wired.com/2016/09/how-to-steal-an-ai/

I'm putting this as help wanted, because I sure as hell want to play with this. Let's figure out how to do it

**Comment by ethangamma24** [comment]
Have you found a specific API that you want to copy?
